name: demo_sapo_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # StateManagement
  flutter_bloc:
  tuple:
  freezed_annotation:
  # JsonParser
  json_annotation:
  # Http Client
  dio:
  #Svg Loader
  flutter_svg: ^0.22.0
  # Local Persist
  shared_preferences:
  # Simple direct Service Locator
  get_it:
  #auth_nav
  auth_nav:
    git: https://github.com/dangngocduc/auth_nav

  oauth2_dio:
    git: https://github.com/dangngocduc/oauth2_dio

  fl_paging:

  carousel_slider: ^4.0.0

  pin_code_fields: ^7.2.0

  tiengviet:

  cached_network_image: ^3.1.0

  intl:

  flutter_screenutil:

  flutter_html: ^2.1.5

  expandable_text: ^2.2.0
  menu_button: ^1.4.2+1
  dropdown_search: ^1.0.0
  dotted_decoration: ^2.0.0
  dart_ipify: ^1.1.1
  qr_code_scanner: ^0.6.1
  permission_handler:
  timelines:
  hydrated_bloc: ^7.1.0
  share_plus: ^3.0.4
  syncfusion_flutter_barcodes: ^19.3.56

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed:
  flutter_lints: ^1.0.4
flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/image_logo.png"
  remove_alpha_ios: true

  fonts:
    - family: SFProDisplayBold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 800
    - family: SFProDisplaySemiBold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
    - family: SFProDisplayThin
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200

